### ISSUE TITLE
cytoolz fails to install on termux

### ISSUE THREAD

**Issue by GamingKing2436** [pytoolz/cytoolz#198] opened 2023-07-20 05:07 UTC
i run `pip install cytoolz`

and it gives this error output:

```
~ $ pip install cytoolz
Collecting cytoolz
  Using cached cytoolz-0.12.1.tar.gz (503 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [87 lines of output]

      Error compiling Cython file:
      ------------------------------------------------------------
      ...
          cdef readonly object func
          cdef readonly tuple args
          cdef readonly dict keywords
          cdef public object __doc__
          cdef public object __name__
          cdef public object __module__
                             ^
      ------------------------------------------------------------

      cytoolz/functoolz.pxd:18:23: '__module__' redeclared

      Error compiling Cython file:
      ------------------------------------------------------------
      ...
          cdef readonly object func
          cdef readonly tuple args
          cdef readonly dict keywords
          cdef public object __doc__
          cdef public object __name__
          cdef public object __module__
               ^
      ------------------------------------------------------------

      cytoolz/functoolz.pxd:18:9: Compiler crash in AnalyseDeclarationsTransform

      File 'ModuleNode.py', line 203, in analyse_declarations: ModuleNode(functoolz.pxd:1:0,
          full_module_name = 'cytoolz.functoolz',
          is_pxd = True)
      File 'Nodes.py', line 393, in analyse_declarations: StatListNode(functoolz.pxd:1:0)
      File 'Nodes.py', line 5449, in analyse_declarations: CClassDefNode(functoolz.pxd:10:5,
          as_name = 'curry',
          class_name = 'curry',
          in_pxd = True,
          module_name = '',
          punycode_class_name = 'curry',
          visibility = 'private')
      File 'Nodes.py', line 393, in analyse_declarations: StatListNode(functoolz.pxd:11:4)
      File 'Nodes.py', line 1529, in analyse_declarations: CVarDefNode(functoolz.pxd:18:9,
          in_pxd = True,
          modifiers = [...]/0,
          visibility = 'public')

      Compiler crash traceback from this point on:
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-a1a7gex9/overlay/lib/python3.11/site-packages/Cython/Compiler/Nodes.py", line 1529, in analyse_declarations
          self.entry = dest_scope.declare_var(
                       ^^^^^^^^^^^^^^^^^^^^^^^
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-a1a7gex9/overlay/lib/python3.11/site-packages/Cython/Compiler/Symtab.py", line 2388, in declare_var
          entry = self.declare(name, cname, type, pos, visibility)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-a1a7gex9/overlay/lib/python3.11/site-packages/Cython/Compiler/Symtab.py", line 550, in declare
          entries[name].already_declared_here()
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-a1a7gex9/overlay/lib/python3.11/site-packages/Cython/Compiler/Symtab.py", line 262, in already_declared_here
          error(self.pos, "Previous declaration is here")
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-a1a7gex9/overlay/lib/python3.11/site-packages/Cython/Compiler/Errors.py", line 178, in error
          raise InternalError(message)
      InternalError: Internal compiler error: Previous declaration is here
      [1/5] Cythonizing cytoolz/dicttoolz.pyx
      [2/5] Cythonizing cytoolz/functoolz.pyx
      Traceback (most recent call last):
        File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-a1a7gex9/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 341, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-a1a7gex9/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 323, in _get_build_requires
          self.run_setup()
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-a1a7gex9/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 488, in run_setup
          self).run_setup(setup_script=setup_script)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-a1a7gex9/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 338, in run_setup
          exec(code, locals())
        File "<string>", line 85, in <module>
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-a1a7gex9/overlay/lib/python3.11/site-packages/Cython/Build/Dependencies.py", line 1134, in cythonize
          cythonize_one(*args)
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-a1a7gex9/overlay/lib/python3.11/site-packages/Cython/Build/Dependencies.py", line 1301, in cythonize_one
          raise CompileError(None, pyx_file)
      Cython.Compiler.Errors.CompileError: cytoolz/functoolz.pyx
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
~ $
```

i also tried adding --only_binary :all: but there seems to be no compatible wheels
```
ERROR: Could not find a version that satisfies the requirement cytoolz (from versions: none)
ERROR: No matching distribution found for cytoolz
```

there was definitely some way i did it before, it was installed, but while trying to fix a different issue i uninstalled cytoolz, and i forgot how i installed cytoolz before.

**Comment by GamingKing2436** [comment] 2023-07-20 05:12
forgot to mention, also happens with `0.12.0`.

**Comment by romanovj** [comment] 2023-07-20 06:44
> forgot to mention, also happens with `0.12.0`.

problem with cython

echo "cython<3.0" >> c.txt
PIP_CONSTRAINT=c.txt pip install cytoolz

**Comment by opoplawski** [comment] 2023-07-20 14:01
Fedora is transitioning to cython 3, so it would be nice to have it supported in cytoolz.

**Comment by opoplawski** [comment] 2023-07-20 14:02
This is likely a duplicate of #197

**Comment by GamingKing2436** [comment] 2023-07-20 16:13
> > forgot to mention, also happens with `0.12.0`.
> 
> problem with newest cython
> 
> echo "cython<3.0" >> c.txt PIP_CONSTRAINT=c.txt pip install cytoolz

thanks, that works

**Closed** 2023-09-17 02:21 UTC
